title: Cloudera Labs
description: Database of Information

permalink: pretty

search_enabled: true
auto_page_title: true

mermaid_enabled: true
mermaid_theme: forest

sidebar:
  - label: Ansible Foundry
    children:
      - ansible_intro
      - ansible_developers
      - ansible_info
      - ansible_troubleshoot
  - label: CDP PvC Data Services
    children:
      - ecs_env
      - ecs_gpu
  - development

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

exclude:
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .prettierrc
  - .prettierignore
  - .tool-versions
  - Gemfile
  - LICENSE*
  - node_modules
  - package.json
  - package-lock.json
  - README*
  - '*.gemspec'
  - '*.config.js'

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
